services:
  - type: web
    name: xtinna-site
    env: static
    buildCommand: npm install && npm run build --prod
    publishDir: dist/xtinna-site
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
